# Generated by Django 4.1.2 on 2022-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='mobile_number',
            field=models.IntegerField(default=123456789, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
