# Generated by Django 4.1.2 on 2022-11-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='base_profile',
            new_name='user',
        ),
    ]
