# Generated by Django 4.1.2 on 2022-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_base_profile_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='teacher', editable=False, max_length=10),
        ),
    ]
