# Generated by Django 4.1.2 on 2022-11-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_mobile_number_alter_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
