# Generated by Django 4.1.2 on 2022-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='teacher', max_length=10),
        ),
    ]
