# Generated by Django 4.1.2 on 2022-11-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_mobile_number_alter_teacher_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id']},
        ),
    ]
