# Generated by Django 4.1.2 on 2022-11-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_delete_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['id']},
        ),
    ]
