# Generated by Django 4.1.2 on 2022-11-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_user_is_admin_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
