# Generated by Django 4.1.2 on 2022-11-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'STUDENT')], default='STUDENT', max_length=10)),
                ('enrolled_course', models.ManyToManyField(to='course.course')),
            ],
        ),
    ]
