# Generated by Django 4.1.2 on 2022-11-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='base_profile',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', editable=False, max_length=10),
        ),
    ]
