# Generated by Django 4.1.2 on 2022-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
