# Generated by Django 4.1.2 on 2022-11-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('student', '0003_student_mobile_number_alter_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_course',
            field=models.ManyToManyField(blank=True, to='course.course'),
        ),
    ]
