# Generated by Django 4.1.2 on 2022-11-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_base_profile_student_user_alter_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT')], default='STUDENT', max_length=10),
        ),
    ]
